### ISSUE TITLE
Still Maintained ?

### ISSUE THREAD

**Issue by SyCode7** [br3nt/OMP4J#1]
Hi, this is a good work. Can I know if this is still maintained or integrated into something else ?
Could you also provide some guidelines as to how to use this..like a README.
Thanks.

**Comment by br3nt** [comment]
Hi @SyCode7, I developed this library as part of a uni project several years ago, so at this point it is not maintained.

For an example of how it all fits together and works have a look at the `main` method in [`OMP4J/src/com/omp4j/omp/Client.java`](https://github.com/br3nt/OMP4J/blob/master/src/com/omp4j/omp/Client.java).  It shows connecting to `omp`, creating and running a task, and then printing the generated report.  Each step is an example of sending and receiving responses to and from `omp`. 

The `com.omp4j.opm.Client` is the entry point into the library.

The `execute` method is the lowest level method which sends commands to `omp` via the command line.  It accepts subclasses of `com.omp4j.commands.OMPCommand`.

An `com.omp4j.commands.OMPCommand` is little more than an xml document with helper methods.  Each of the subclasses creates the necessary xml required to interact with `omp`.

The `com.omp4j.opm.Client#parseResponse` method converts the response from `omp` into an XML document.  The resulting document can be passed into the corresponding `com.omp4j.responses.OMPResponse` subclasses to extract some useful information.  Each of the predefined command methods already parse the `omp` xml response into the correct subclass.

I hope my reply does not come too late and is of some assistance to you.

Feel free to submit pull requests for any fixes that may be required.

**Comment by br3nt** [comment]
I've updated the readme so it contains the above information too.
