### ISSUE TITLE
[Fatal Error] omp-5-0.html:1:1: Premature end of file.

### ISSUE THREAD

**Issue by rstarlet** [br3nt/OMP4J#2]
Hello sir, 
I am trying to use your code, but it is showing errors on parsing...i have used your code as you have mentioned in docs.

ant -f /home/hacktivist/NetBeansProjects/OMP4J -Dnb.internal.action.name=run run
init:
Deleting: /home/hacktivist/NetBeansProjects/OMP4J/build/built-jar.properties
deps-jar:
Updating property file: /home/hacktivist/NetBeansProjects/OMP4J/build/built-jar.properties
Proc.init:
Proc.deps-jar:
Updating property file: /home/hacktivist/NetBeansProjects/OMP4J/build/built-jar.properties
Proc.compile:
Proc.jar:
Compiling 1 source file to /home/hacktivist/NetBeansProjects/OMP4J/build/classes
warning: [options] bootstrap class path not set in conjunction with -source 1.7
1 warning
compile:
run:
===  Get ConfigID for Full and Fast =============================
listener: start
command: 
omp -u admin -w password -h 10.0.0.2 -p 9390 -iX <?xml version="1.0"?>
<get_configs />

error: Failed to authenticate.
listener: finished
has output? false
has errors? true
exitValue: 1

[Fatal Error] omp-5-0.html:1:1: Premature end of file.
Apr 16, 2017 6:31:43 PM com.omp4j.omp.Client main
SEVERE: null
nu.xom.ParsingException: Premature end of file. at line 1, column 1 in http://www.openvas.org/omp-5-0.html
	at nu.xom.Builder.build(Unknown Source)
	at nu.xom.Builder.build(Unknown Source)
	at nu.xom.Builder.build(Unknown Source)
	at com.omp4j.omp.Client.parseResponse(Client.java:42)
	at com.omp4j.omp.Client.getConfigs(Client.java:49)
	at com.omp4j.omp.Client.main(Client.java:117)
Caused by: org.xml.sax.SAXParseException; systemId: http://www.openvas.org/omp-5-0.html; lineNumber: 1; columnNumber: 1; Premature end of file.
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1239)
	... 6 more

**Comment by br3nt** [comment]
You're getting an error message in the output saying `error: Failed to authenticate`.

First and foremost, I assume this error means either your username or password is incorrect.  You'll want to check that out first.

Next, `Client.main` is only an example of how to use the `Client` class.  I recommend creating your own subclass to handle errors in the way you want.

You can catch and handle any errors in your `main` method:

```java
public class YourClient extends Client {
  // your implementation goes here
  public static void main(String... args) {
    try {
      String host = "10.0.0.19", scanType = "Full and fast";      
      Client omp = new Client("admin", "password");
      System.out.println("Get ConfigID for Full and Fast");
      GetConfigsResponse cr = omp.getConfigs();
      // etc
    }
    catch (ParsingException ex) {
      // Oops! Something went wrong... handle in some custom way
    }
  }
}
```

or, you can override instance methods to provide custom handling:

```java
public class YourClient extends Client {

  public GetConfigsResponse getConfigs() throws IOException, InterruptedException, ParsingException {
    try {
      return super.getConfigs();
    catch (ParsingException ex) {
      // Oops! Something went wrong... handle in some custom way
    }
  }   

  // your implementation goes here
  public static void main(String... args) {
    String host = "10.0.0.19", scanType = "Full and fast";      
    Client omp = new Client("admin", "password");
    System.out.println("Get ConfigID for Full and Fast");
    GetConfigsResponse cr = omp.getConfigs();
    // etc
  }
}
```

**Comment by br3nt** [comment]
Let me know if any of my suggestions above helped or not.
